sampling:
  main_interval: 1h
  overlay_decay_hours: 2

symbol_pool:
  # 每天 00:00 UTC 基础池规模（更大覆盖更广）
  base_pool_daily_size: 260
  # 每小时最终保留的“最强候选”上限（不是扫描上限）
  max_symbols: 60
  # 24h 报价额门槛（USDT）
  min_quote_vol: 15000000

scan:
  # 每小时参与扫描的最大币数（真正决定“扫多少”）
  max_symbols_per_scan: 220
  # 每个币之间暂停（毫秒）— 提高以降低限流风险
  per_symbol_pause_ms: 600
  # 兼容老字段名（与上面取同值）
  per_symbol_delay_ms: 600
  # 24h tickers 缓存秒数（减少频次）
  tickers_cache_sec: 900
  # 命中 418/429/-1003 的退避时间（毫秒）
  backoff_ms_418_429_1003: 2500

overlay:
  # 叠加热点窗口规模（适当增大配合更广覆盖）
  top_movers: 80

thresholds:
  trend:
    ema30_slope_min: 0.25
    r2_min: 0.45
  struct:
    zigzag_min_atr:
      base: 0.4
      overlay: 0.6
    score_gate:
      base: 0.7
      overlay: 0.75
      phaseA: 0.78
  volume:
    vboost_min:
      base: 1.8
      overlay: 2.7
      phaseA: 3.2
    cvd_mix_pct:
      long: 0.12
      short: -0.12
    tib_abs_min:
      base: 0.2
      overlay: 0.3
  aplus:
    min_total: 90
    block_min: 65
    chop_add: 5
  gates:
    A:
      lookback: 72
      breakout_pad: 0.002
      close_outside: 0.003
      body_atr_max:
        default: 1.2
        phaseA: 1.0
    B:
      anchors:
        L2_ema10_atr: 0.05
        L1_breakout_atr: 0.1
        L3_avwap_atr: 0.05
      confirm:
        vboost: 1.3
        tib_abs: 0.2
        body_pct_min: 0.35
        close_zone: 0.35
        pullback_atr_max: 0.5
        phaseA_pullback_tr: 0.45
    C:
      funding_pctl:
        big: 90
        small: 95
      speed_pctl: 75
      z_extreme:
        big: 1.8
        small: 2.3
    D:
      impact_bps: 10
      obi_abs: 0.3
      spread_bps: 25
      room_atr_min: 0.6
      cost_R_max: 0.12

planner:
  weights:
    default: [0.6, 0.3, 0.1]
    hi:      [0.7, 0.2, 0.1]
    lo:      [0.5, 0.4, 0.1]
  tick_nudge_sec: 25

risk:
  RISK_PCT: 0.005
  RISK_USDT_CAP: 6
  RISK_USDT_FLOOR: 3
  MAX_CONCURRENT_POS: 3
  HOURLY_RISK_BUDGET_PCT: 0.015
  MAX_PORTFOLIO_RISK_PCT: 0.02
  cooldown:
    loss: 8h
    profit: 3h
  breadth:
    open_threshold: 0.6
    tighten_threshold: 0.35
  bucket:
    BTC: 2
    ETH: 2
    SOL: 2
    BNB: 2
    OTHER: 2
  cluster:
    lookback_days: 7
    corr_threshold: 0.65